// SPDX-License-Identifier: MIT

pragma solidity =0.8.13;

contract Check4 {
    struct Len {
        uint256 l;
    }

    function checkBatchYul(Len calldata l) external returns (uint256 r) {
        assembly {
            let input := calldataload(4)
            let len := div(input, 100)
            for {
                let i := 0
            } lt(i, len) {
                i := add(i, 1)
            } {
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
                r := mulmod(r, 10, 26)
            }
        }
    }
}